version: '3.7'
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "aggregator"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password1234"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - local-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  local-data: